# Generated by Django 4.0.6 on 2022-07-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Simple', 'Simple'), ('Doble', 'Matrimonial'), ('Suite', 'Suite')], max_length=10, verbose_name='Tipo de habitación')),
                ('description', models.TextField(verbose_name='Detalles')),
                ('price', models.PositiveIntegerField(default=10, verbose_name='Precio por noche')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima edición')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
            },
        ),
    ]
