# Generated by Django 4.0.6 on 2022-07-08 19:26

from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('status', models.CharField(choices=[('Pendiente', 'Pending'), ('Pagado', 'Paid'), ('Eliminado', 'Deleted')], default='Pendiente', max_length=10, verbose_name='Estado')),
                ('reservation_date', models.DateTimeField(auto_now_add=True, verbose_name='Día de reservación')),
                ('checkin', models.DateField(verbose_name='Ingreso')),
                ('checkout', models.DateField(verbose_name='Salida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima edición')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer', verbose_name='ID cliente')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='Habitación')),
            ],
            options={
                'verbose_name': 'Reservación',
                'verbose_name_plural': 'Reservaciones',
            },
        ),
    ]
