# Generated by Django 4.0.6 on 2022-07-08 19:28

from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservation', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('pay_method', models.CharField(choices=[('tarjeta', 'Ccard'), ('efectivo', 'Cash'), ('qr', 'Qr')], default='tarjeta', max_length=10, verbose_name='Estado')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('payment_date', models.DateField(auto_now_add=True, verbose_name='Día del pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima edición')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer', verbose_name='ID cliente')),
                ('reservations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation', verbose_name='Reservación')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
